name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: "x86_64-unknown-linux-gnu"
            cross: true
          - target: "x86_64-pc-windows-gnu"
            cross: true
          #- target: "aarch64-apple-darwin"
          #  cross: true
          - target: "x86_64-apple-darwin"
            cross: true
    steps:
    - uses: actions/checkout@v3
    - name: Install toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        override: true
        toolchain: stable
        target: ${{ matrix.target }}
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --target=${{ matrix.target }}
        use-cross: ${{ matrix.cross }}
