name: Rust

on:
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      matrix:
        include:
          - target: "x86_64-unknown-linux-gnu"
            os: "ubuntu-latest"
            cross: false
            output: model
            asset-name: model-linux-x86_64
            compress-binary: true
          - target: "x86_64-pc-windows-gnu"
            os: "ubuntu-latest"
            cross: true
            output: model.exe
            asset-name: model-windows-x86_64
            compress-binary: true
          - target: "aarch64-apple-darwin"
            os: "macOS-latest"
            cross: true
            output: model
            asset-name: model-macos-aarch64
            compress-binary: false
          - target: "x86_64-apple-darwin"
            os: "macOS-latest"
            cross: false
            output: model
            asset-name: model-macos-x86_64
            compress-binary: false
    steps:
      - uses: actions/checkout@v3
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          override: true
          toolchain: stable
          target: ${{ matrix.target }}
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target=${{ matrix.target }}
          use-cross: ${{ matrix.cross }}
      - name: Rename assets
        run: cp target/${{ matrix.target }}/release/${{ matrix.output }} ${{ matrix.asset-name }}
      - name: Compress output
        run: |
          wget https://github.com/upx/upx/releases/download/v3.96/upx-3.96-amd64_linux.tar.xz
          tar xvf upx-3.96-amd64_linux.tar.xz
          upx-3.96-amd64_linux/upx ${{ matrix.asset-name }}
        if: ${{ matrix.compress-binary }}
      - name: Check binary runs
        run: ./${{ matrix.asset-name }}
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ matrix.asset-name }}
