name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - "x86_64-apple-darwin"
          - "x86_64-pc-windows-gnu"
          - "aarch64-apple-darwin"
          - "x86_64-apple-darwin"
    steps:
    - uses: actions/checkout@v3
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --target=${{ matrix.target }}
        use-cross: true
